import { HeroSpecials } from './herospecials';

export const HEROSPECIALS: HeroSpecials[] = [
{id:0,name:"-"},
{id:1,name:"Aegis"},
{id:2,name:"Aether"},
{id:3,name:"Astra"},
{id:4,name:"Blazing Flame"},
{id:5,name:"Blazing Light"},
{id:6,name:"Blazing Thunder"},
{id:7,name:"Blazing Wind"},
{id:8,name:"Bonfire"},
{id:9,name:"Buckler"},
{id:10,name:"Chilling Wind"},
{id:11,name:"Daylight"},
{id:12,name:"Draconic Aura"},
{id:13,name:"Dragon Fang"},
{id:14,name:"Dragon Gaze"},
{id:15,name:"Escutcheon"},
{id:16,name:"Galeforce"},
{id:17,name:"Glacies"},
{id:18,name:"Glimmer"},
{id:19,name:"Glowing Ember"},
{id:20,name:"Growing Flame"},
{id:21,name:"Growing Light"},
{id:22,name:"Growing Thunder"},
{id:23,name:"Growing Wind"},
{id:24,name:"Heavenly Light"},
{id:25,name:"Holy Vestments"},
{id:26,name:"Iceberg"},
{id:27,name:"Ignis"},
{id:28,name:"Imbue"},
{id:29,name:"Kindled-Fire Balm"},
{id:30,name:"Luna"},
{id:31,name:"Miracle"},
{id:32,name:"Moonbow"},
{id:33,name:"New Moon"},
{id:34,name:"Night Sky"},
{id:35,name:"Noontime"},
{id:36,name:"Pavise"},
{id:37,name:"Reprisal"},
{id:38,name:"Retribution"},
{id:39,name:"Rising Flame"},
{id:40,name:"Rising Light"},
{id:41,name:"Rising Thunder"},
{id:42,name:"Rising Wind"},
{id:43,name:"Sacred Cowl"},
{id:44,name:"Sol"},
{id:45,name:"Solid-Earth Balm"},
{id:46,name:"Still-Water Balm"},
{id:47,name:"Swift-Winds Balm"},
{id:48,name:"Vengeance"}
]